version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/n8n" # Location of package manifests
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
