ARG N8N_VERSION

FROM  n8nio/n8n:${N8N_VERSION}
LABEL org.opencontainers.image.source=https://github.com/kagemomiji/docker
LABEL org.opencontainers.image.description="Custom n8n image"

RUN chmod u+s /bin/ping
