FROM n8nio/n8n:1.22.4
LABEL org.opencontainers.image.source=https://github.com/kagemomiji/docker
LABEL org.opencontainers.image.description="Custom n8n image"
USER root
RUN chmod u+s /bin/ping
USER node
