name: Build and push

on:
  workflow_call:
    inputs:
      tag: 
        required: true
        type: string
        description: build docker image tag
      version:
        required: false
        type: string
        description: docker image tag version. default value is set from version file.
      context:
        required: true
        type: string
        description: build context
    
defaults:
  run:
    shell: bash

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ github.token }} 
      
      - name: version
        id: version
        working-directory: ${{ inputs.context }}
        run: |
          if [ ! -f "version" ]; then
            echo $(pwd)
            echo "Not found version file"
            exit 1;
          fi
          echo "value=$(cat version)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ inputs.tag }}:${[ inputs.version || steps.outputs.version.value ]}
          context: ${{ inputs.context }}
          build-args: |
            VERSION=${{steps.version.outputs.value}}
