name: Build and push

on:
  workflow_call:
    inputs:
      tag: 
        required: true
        type: string
        description: build docker image tag
      version:
        required: false
        type: string
        description: docker image tag version. default value is set from version file.
      context:
        required: true
        type: string
        description: build context

permissions: 
  packages: write
    
defaults:
  run:
    shell: bash

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ github.token }} 
      
      - name: version
        id: version
        working-directory: ${{ inputs.context }}
        env: 
          IMAGE: ${{inputs.context}}
        run: |
          if [ ! -f "Dockerfile" ]; then
            echo $(pwd)
            echo "Not found Dockerfile"
            exit 1;
          fi
          echo "value=$(sed -n -e "s/^FROM.*$IMAGE:\(.*\)$/\1/p" Dockerfile)" >> $GITHUB_OUTPUT

      - name: tag
        id: tag
        env: 
          TAG: ${{inputs.tag}}
          INPUT_VERSION: ${{inputs.version}}
          FILE_VERSION: ${{steps.version.outputs.value}}
        run: |
          if [ -n "${INPUT_VERSION}" ]; then
            echo "value=${TAG}:${INPUT_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "value=${TAG}:${FILE_VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.tag.outputs.value }}
          context: ${{ inputs.context }}
          build-args: |
            VERSION=${{steps.version.outputs.value}}
